// Builds worker/src/parser/parser.gen.js from the Apps Script parser files
// (BankTemplates.js + Parser.js at the repo root) by appending ES exports.
// The root files stay the single source of truth until the D1 cutover.
//
//   node worker/scripts/sync-parser.mjs          # regenerate
//   node worker/scripts/sync-parser.mjs --check  # exit 1 if stale (CI)
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(here, "../..");
export const OUTPUT = resolve(here, "../src/parser/parser.gen.js");
const SOURCES = ["BankTemplates.js", "Parser.js"];

export const EXPORTS = [
  "BANK_TEMPLATES",
  "PARSER_AUTO_SAVE_CONFIDENCE",
  "PARSER_REVIEW_CONFIDENCE",
  "PARSER_TEMPLATE_CONFIDENCE",
  "PARSER_GENERIC_ID",
  "PARSER_MAX_AMOUNT",
  "PARSER_COMPARED_FIELDS",
  "normalizeTransactionText",
  "looksLikeTransactionText",
  "splitSmsPaste",
  "parseTransactionText",
  "validateExtraction",
  "guessCategory",
  "diffExtractions",
  "toIsoDate"
];

export function buildParserModule(root = ROOT) {
  const parts = SOURCES.map((f) => "// ---- " + f + " ----\n" + readFileSync(resolve(root, f), "utf8").trim() + "\n");
  return (
    "// GENERATED by worker/scripts/sync-parser.mjs — do not edit.\n" +
    "// Edit BankTemplates.js / Parser.js at the repo root, then run `npm run parser:sync`.\n\n" +
    parts.join("\n") +
    "\nexport {\n" +
    EXPORTS.map((n) => "  " + n).join(",\n") +
    "\n};\n"
  ).replace(/\r\n/g, "\n");
}

function main() {
  const next = buildParserModule();
  if (process.argv.includes("--check")) {
    const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8").replace(/\r\n/g, "\n") : "";
    if (current !== next) {
      console.error("worker/src/parser/parser.gen.js is stale — run `npm run parser:sync`.");
      process.exit(1);
    }
    console.log("parser.gen.js is up to date.");
    return;
  }
  writeFileSync(OUTPUT, next);
  console.log("Wrote " + OUTPUT);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
