name: Deploy to Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp@2.4.2

      - name: Create Lol.js from secrets
        run: |
            printf "// Telegram\n" > Lol.js
            printf "const BOT_TOKEN = \"${{ secrets.BOT_TOKEN }}\";\n" >> Lol.js
            printf "const PERSONAL_CHAT_ID = \"${{ secrets.PERSONAL_CHAT_ID }}\";\n" >> Lol.js
            printf "const GROUP_CHAT_ID = \"${{ secrets.GROUP_CHAT_ID }}\";\n\n" >> Lol.js
            printf "const SCRIPT_APP_URL = \"${{ secrets.SCRIPT_APP_URL }}\";\n\n" >> Lol.js
            printf "const TEST_SCRIPT_APP_URL = \"${{ secrets.TEST_SCRIPT_APP_URL }}\";\n\n" >> Lol.js
            printf "// Google Sheets\n" >> Lol.js
            printf "const TEST_SHEET_ID = \"${{ secrets.TEST_SHEET_ID }}\";\n" >> Lol.js
            printf "const PROD_SHEET_ID = \"${{ secrets.PROD_SHEET_ID }}\";\n" >> Lol.js
            printf "const SHEET_NAME = \"${{ secrets.SHEET_NAME }}\";\n\n" >> Lol.js
            printf "// Gemini\n" >> Lol.js
            printf "const GEMINI_BASE_URL = \"${{ secrets.GEMINI_BASE_URL }}\";\n" >> Lol.js
            printf "const GEMINI_API_KEY = \"${{ secrets.GEMINI_API_KEY }}\";\n\n" >> Lol.js
            printf "// Gmail\n" >> Lol.js
            printf "const GMAIL_LABEL = \"${{ secrets.GMAIL_LABEL }}\";" >> Lol.js

      - name: Set up authentication
        env:
          CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
        run: |
          echo $CLASP_TOKEN > ~/.clasprc.json
          cat ~/.clasprc.json

      - name: Push to Apps Script
        run: clasp push
