name: Deploy to Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp@2.4.2

      - name: Set up authentication
        env:
          CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
        run: |
          echo $CLASP_TOKEN > ~/.clasprc.json
          cat ~/.clasprc.json

      - name: Push to Apps Script
        run: clasp push
